# Dev env compose file

version: '2'

volumes:
    pgdata4:
    pglogs:

services:

    django:
        build:
            context: .
        volumes:
            - ./:/source
        working_dir: /source/urbana
        command: bash -c ". ../run_django.sh"
        ports:
            - 80:80
            - 35729:35729
        depends_on:
            - pg_database
        env_file: env

    pg_database:
        image: postgres:9.5.3
        # secret strings are in the file
        env_file: env
        volumes:
            # override postgres image Dockerfile data volume
            - pgdata4:/var/lib/postgresql/data  # TODO: rename pgdata4
            - pglogs:/var/log/postgresql
            - ./:/source/dumps  # volume mounted to get dump files out of container
        ports:
            # expose ports to the docker host for debug purposes
            - 5432:5432